name: Compile LaTeX Slides to PDF

on:
  push:
    branches: [main]

jobs:
  compile-pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install LaTeX (TeX Live)
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex texlive-fonts-extra texlive-latex-extra


    - name: Compile LaTeX to PDF
      run: |
        mkdir pdfs
        for file in Slides/*.tex; do
          filename=$(basename "$file" .tex)
          xelatex -interaction=nonstopmode -output-directory=pdfs "$file"
        done

    - name: Deploy PDFs to 'pdf' branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git fetch origin pdf || true
        git switch --orphan pdf
        cp pdfs/*.pdf .
        git add .
        git commit -m "Update PDFs (XeLaTeX)"
        git push --force "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" HEAD:pdf